# Generated by Django 5.0.7 on 2024-07-21 16:33

import django.db.models.deletion
import products.helpers
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(null=True, upload_to=products.helpers.SaveMedia.save_book_image_path)),
                ('description', models.TextField()),
                ('price', models.IntegerField()),
                ('rating', models.IntegerField()),
                ('count', models.IntegerField()),
                ('country_of_origin', models.CharField(max_length=50)),
                ('Quality', models.CharField(max_length=50)),
                ('Check', models.CharField(max_length=50)),
                ('Min_weight', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.category')),
            ],
        ),
    ]
