# Generated by Django 5.0.7 on 2024-07-21 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_category_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='value',
            field=models.CharField(default=1, max_length=120),
            preserve_default=False,
        ),
    ]
