# Generated by Django 5.0.7 on 2024-07-21 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Featured_products',
            field=models.BooleanField(default=False),
        ),
    ]
